In [1]:
import numpy as np 
import pandas as pd 
import networkx as nx
from sklearn.neighbors import DistanceMetric
from math import radians

In [2]:
df = pd.read_csv("data/bank_data.csv")
dc = df.copy()

In [3]:
dc['money_and_time_ratio'] = dc['money']/ dc['time (hr)']

In [4]:
dc['distance_to_(0,0)'] = (dc['x_coordinate']**2 + dc['y_coordinate']**2)**1/2

In [5]:
sample = dc.iloc[[0,1,2,3,4,5]]
#sample

In [6]:
destiance_mon_time_ratio = dc.sort_values(['money_and_time_ratio'], ascending = False)

In [7]:
dc['distance_money_time_ratio_(0,0)'] = dc['money']/ (dc['time (hr)'] * dc['distance_to_(0,0)'])

In [8]:
dc.sort_values(['distance_money_time_ratio_(0,0)'], ascending = False)

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)","distance_money_time_ratio_(0,0)"
3613,3613,-1.950527,-1.495858,54400,0.000186,2.929603e+08,3.021073,9.697227e+07
8789,8789,0.084917,0.003973,93200,0.464666,2.005742e+05,0.003613,5.550951e+07
9546,9546,-1.810721,-0.795421,75100,0.000788,9.530556e+07,1.955703,4.873211e+07
5135,5135,-0.404042,-0.433493,73900,0.009476,7.799032e+06,0.175583,4.441797e+07
1212,1212,0.012560,0.094192,40100,0.290822,1.378850e+05,0.004515,3.053962e+07
...,...,...,...,...,...,...,...,...
2379,2379,-4.466583,4.447707,100,1.369681,7.300970e+01,19.866233,3.675065e+00
3304,3304,-4.143795,4.641069,100,1.408332,7.100597e+01,19.355279,3.668558e+00
7687,7687,-4.167891,4.522109,100,1.476305,6.773667e+01,18.910391,3.581982e+00
3343,3343,4.776344,-4.978566,100,1.173772,8.519545e+01,23.799787,3.579673e+00
3068,3068,4.351864,4.412940,100,1.479056,6.761071e+01,19.206380,3.520221e+00

In [9]:
dc.describe()

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)","distance_money_time_ratio_(0,0)"
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,1.000000e+04
mean,4999.50000,-0.016431,0.037561,18430.320000,0.750245,1.377386e+05,8.327162,6.154768e+04
std,2886.89568,2.889568,2.881789,25382.131155,0.433541,3.212502e+06,5.319796,1.369983e+06
min,0.00000,-4.999292,-4.999928,100.000000,0.000032,6.668374e+01,0.001516,3.520221e+00
25%,2499.75000,-2.513854,-2.415033,900.000000,0.373141,1.489860e+03,3.911300,2.337639e+02
50%,4999.50000,-0.024904,0.010442,5800.000000,0.749218,9.921099e+03,7.932445,1.571485e+03
75%,7499.25000,2.461754,2.540303,26900.000000,1.122812,4.614359e+04,11.907404,7.501915e+03
max,9999.00000,4.999851,4.999626,102300.000000,1.499851,2.929603e+08,24.771480,9.697227e+07

In [112]:
dc100distance = destiance_mon_time_ratio[:100]
#dc100distance # only 100 banks to test your code

In [113]:
dc100distance

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)"
3613,3613,-1.950527,-1.495858,54400,0.000186,2.929603e+08,3.021073
9546,9546,-1.810721,-0.795421,75100,0.000788,9.530556e+07,1.955703
3803,3803,3.867586,0.918332,18500,0.000358,5.169381e+07,7.900776
6528,6528,-0.282937,3.224334,33900,0.000769,4.407762e+07,5.238193
9583,9583,3.393835,-2.790830,24000,0.001131,2.121396e+07,9.653426
...,...,...,...,...,...,...,...
7649,7649,-4.872158,2.208422,27500,0.020783,1.323216e+06,14.307528
7689,7689,-2.105993,4.577504,90800,0.069226,1.311637e+06,12.694377
9880,9880,2.845568,-0.548524,42200,0.032338,1.304957e+06,4.199069
3297,3297,-2.796212,-4.028651,79700,0.061625,1.293312e+06,12.024415
4794,4794,0.757128,-4.198354,22900,0.017766,1.288956e+06,9.099710

In [110]:
import numpy as np

p1 = np.array([-1.950527,-1.495858])

p2 = np.array([-1.810721,-0.795421])

a = np.linalg.norm(p1-p2)
a

0.7142532524287165

In [114]:
closest_0_0 = dc.sort_values(['distance_to_(0,0)'], ascending = True)
#closest_0_0

In [115]:
#dc['x_coordinate'] = np.radians(dc['x_coordinate'])
#dc['y_coordinate'] = np.radians(dc['y_coordinate'])

In [117]:
dist = DistanceMetric.get_metric('haversine')

In [118]:
dc100distance

,id,x_coordinate,y_coordinate,money,time (hr),money_and_time_ratio,"distance_to_(0,0)"
3613,3613,-1.950527,-1.495858,54400,0.000186,2.929603e+08,3.021073
9546,9546,-1.810721,-0.795421,75100,0.000788,9.530556e+07,1.955703
3803,3803,3.867586,0.918332,18500,0.000358,5.169381e+07,7.900776
6528,6528,-0.282937,3.224334,33900,0.000769,4.407762e+07,5.238193
9583,9583,3.393835,-2.790830,24000,0.001131,2.121396e+07,9.653426
...,...,...,...,...,...,...,...
7649,7649,-4.872158,2.208422,27500,0.020783,1.323216e+06,14.307528
7689,7689,-2.105993,4.577504,90800,0.069226,1.311637e+06,12.694377
9880,9880,2.845568,-0.548524,42200,0.032338,1.304957e+06,4.199069
3297,3297,-2.796212,-4.028651,79700,0.061625,1.293312e+06,12.024415
4794,4794,0.757128,-4.198354,22900,0.017766,1.288956e+06,9.099710

In [119]:
dc100distance[['x_coordinate','y_coordinate']].to_numpy()

array([[-1.95052692, -1.49585784],
       [-1.81072137, -0.79542122],
       [ 3.86758572,  0.91833156],
       [-0.28293671,  3.22433433],
       [ 3.39383541, -2.79083022],
       [ 3.17357739,  1.64569875],
       [-3.35297428, -0.26422988],
       [ 1.00123036,  4.44642978],
       [-0.46762485,  3.33535283],
       [ 1.96947283,  3.48800784],
       [-4.98934192, -2.05527558],
       [ 2.91373763,  2.78025325],
       [-3.47726206,  0.63109818],
       [-2.85446451, -1.53331506],
       [ 3.62890165,  4.78862439],
       [-1.65520395,  2.71874977],
       [ 0.92867278, -0.84634944],
       [-2.24035163,  1.7108545 ],
       [ 2.91051456,  2.53925328],
       [-4.94735443, -2.06150679],
       [-0.40404154, -0.43349281],
       [ 3.5818128 , -1.32687359],
       [ 0.61160646, -0.92089496],
       [-3.1182807 , -0.09149162],
       [ 3.9270899 , -1.29844921],
       [ 3.38801711,  1.18853135],
       [ 4.21386551,  2.220613  ],
       [ 0.47990867,  3.75798962],
       [-3.55038717, -3.76220742],
       [-1.58590241,  0.00966242],
       [ 2.41028058, -3.56982196],
       [ 4.15488788,  3.62552685],
       [ 4.62896063,  2.84785715],
       [-1.15835434,  3.87151038],
       [-3.27457445,  1.54548861],
       [-3.65919468,  3.1655623 ],
       [-3.29645581, -1.88801103],
       [-2.80583036, -3.19384949],
       [-0.805502  ,  4.78723684],
       [-2.28769092,  2.683756  ],
       [ 2.09738172,  2.25695009],
       [-2.77755616, -3.93757799],
       [-1.48241335, -4.35031031],
       [ 2.39304538,  3.95925759],
       [ 0.09944269,  2.17724381],
       [-3.6804348 ,  2.54756982],
       [-4.66155776, -4.20797861],
       [-2.83052252, -3.65612373],
       [-2.47799733,  3.87480367],
       [ 4.10828856,  1.50230623],
       [-2.14776828,  3.80075182],
       [-3.6810199 ,  3.14364678],
       [-0.68697599, -2.31164729],
       [ 2.32236314, -1.98821412],
       [-2.60678988, -3.43298938],
       [-0.99375325, -1.46754281],
       [-0.56563038, -0.76627686],
       [-1.60096827, -1.32938127],
       [ 2.02335831, -3.80519161],
       [ 3.54826996,  2.59192353],
       [ 2.45333228,  2.22347354],
       [-2.76166685, -0.29002304],
       [ 4.70792367,  2.08986508],
       [-0.5730957 ,  2.87282694],
       [ 2.57224097, -4.99604442],
       [-0.98486054,  2.32025334],
       [-3.16033499,  4.56201105],
       [-4.98341342, -1.51181705],
       [-0.94378652,  1.19465003],
       [-4.39611065, -4.40829637],
       [-4.74883973,  3.095799  ],
       [-1.33456118,  3.52345036],
       [ 2.39425296, -0.57356719],
       [ 2.99861914, -2.02689829],
       [ 4.90533933, -4.47372978],
       [-2.81014951, -0.99415143],
       [ 0.36657005,  0.78961934],
       [-4.18424936,  3.22351855],
       [-0.33126741,  1.58860663],
       [ 3.19319365,  4.4073125 ],
       [-3.87501842, -0.49188022],
       [-0.15766814,  1.21538718],
       [ 2.49224266, -2.52695127],
       [-4.51130658, -0.02374769],
       [-3.70480779, -2.82264594],
       [-3.02476354,  0.00601156],
       [-2.95358186,  0.44600114],
       [ 1.67062401,  1.79228782],
       [ 0.10896043,  1.95694805],
       [-2.68838645,  3.3833795 ],
       [-1.17157746, -1.36308504],
       [ 4.61924848, -3.08819508],
       [-0.03674302, -2.06304302],
       [ 0.72890438,  1.1345921 ],
       [-4.80197171,  3.2991661 ],
       [-4.87215849,  2.20842206],
       [-2.10599304,  4.57750438],
       [ 2.84556844, -0.54852413],
       [-2.7962123 , -4.02865073],
       [ 0.75712797, -4.19835416]])

In [120]:
dist.pairwise(dc[['x_coordinate','y_coordinate']].to_numpy())

array([[0.00000000e+00, 3.77550261e-07, 4.62128421e-07, ...,
        4.95812786e-07, 4.35196989e-07, 6.43428488e-07],
       [3.77550261e-07, 0.00000000e+00, 5.40168540e-07, ...,
        4.33560634e-07, 1.60926357e-07, 7.97353264e-07],
       [4.62128421e-07, 5.40168540e-07, 0.00000000e+00, ...,
        1.83652860e-07, 4.35784172e-07, 2.62223013e-07],
       ...,
       [4.95812786e-07, 4.33560634e-07, 1.83652860e-07, ...,
        0.00000000e+00, 2.95505454e-07, 4.28715747e-07],
       [4.35196989e-07, 1.60926357e-07, 4.35784172e-07, ...,
        2.95505454e-07, 0.00000000e+00, 6.97991129e-07],
       [6.43428488e-07, 7.97353264e-07, 2.62223013e-07, ...,
        4.28715747e-07, 6.97991129e-07, 0.00000000e+00]])

In [121]:
distace_matrix = pd.DataFrame(dist.pairwise(dc100distance[['x_coordinate','y_coordinate']].to_numpy()), columns = dc100distance.id.unique(), index = dc100distance.id.unique())

In [85]:
distace_matrix.loc[96, 90]

0.08123122672564348

In [122]:
distace_matrix

,3613,9546,3803,6528,9583,5933,9195,4757,8550,4499,...,1372,2442,1733,8375,7764,7649,7689,9880,3297,4794
3613,0.000000,0.247593,1.148843,1.311384,1.234968,1.918542,1.645152,2.898228,1.181612,2.527577,...,0.777143,0.392394,1.852821,1.957848,2.759208,2.620061,0.180281,1.634776,1.542472,1.975840
9546,0.247593,0.000000,0.902635,1.140776,1.422625,1.721891,1.574272,2.652448,0.983169,2.774977,...,0.614445,0.309324,1.606018,2.195262,2.840951,2.742819,0.427785,1.633800,1.464398,2.094759
3803,1.148843,0.902635,0.000000,0.840618,2.031908,0.952648,1.432850,1.757417,0.644987,2.598136,...,0.641350,0.907291,0.704166,2.980187,2.230341,2.330054,1.328845,1.690532,1.171981,2.304721
6528,1.311384,1.140776,0.840618,0.000000,2.544508,1.554344,0.601757,1.629005,0.211502,2.235929,...,1.358504,1.380961,1.009711,2.142636,1.764395,1.767194,1.435989,0.849945,2.000279,1.470618
9583,1.234968,1.422625,2.031908,2.544508,0.000000,1.829305,2.542221,2.108540,2.405744,1.424366,...,1.393580,1.229611,2.365084,1.218224,1.910912,1.865010,1.109391,2.277172,1.178493,1.860660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7649,2.620061,2.742819,2.330054,1.767194,1.865010,1.737632,1.235378,0.678808,1.964967,0.468810,...,2.879468,3.008421,1.675102,0.775394,0.142400,0.000000,2.483410,1.127349,2.075764,0.655347
7689,0.180281,0.427785,1.328845,1.435989,1.109391,2.061295,1.687212,3.064765,1.327609,2.347674,...,0.920014,0.525011,2.032941,1.782001,2.625743,2.483410,0.000000,1.625673,1.607466,1.870733
9880,1.634776,1.633800,1.690532,0.849945,2.277172,2.174226,0.287766,1.468770,1.049850,1.534228,...,2.122219,1.943120,1.635322,1.292968,1.207175,1.127349,1.625673,0.000000,2.816745,0.630570
3297,1.542472,1.464398,1.171981,2.000279,1.178493,0.672440,2.529223,1.560622,1.815910,1.763091,...,0.880177,1.171609,1.187357,2.130952,1.960024,2.075764,1.607466,2.816745,0.000000,2.705949
4794,1.975840,2.094759,2.304721,1.470618,1.860660,2.317851,0.872384,1.266346,1.676342,0.944806,...,2.695609,2.365860,1.997439,0.687692,0.785870,0.655347,1.870733,0.630570,2.705949,0.000000

In [123]:
Y = DistanceMetric.get_metric('euclidean')

In [124]:
def haversine_vectorize(x1, y1, x2, y2):
    x1, y1, x2, y2 = map(np.radians, [x1, y1, x2, y2])
    
    new_x = x2 - x1
    new_y = y2 - y1
    
    haver_formula = np.sin(new_y/2.0)**2 + np.cos(y1) * np.cos(y2) * np.sin(new_x/2.0)**2
    dist_ = 2 * np.arcsin(np.sqrt(haver_formula))
    km =  6373 * dist_ # to get dist in km
    return km

haversine_vectorize(0.022189, -0.001545, 0.043129, -0.010346)

2.526512136954726